{% set version = "0.15.35" %}
# The version_info tuple in __init__.py must also be updated

package:
  name: ruamel_yaml
  version: {{ version }}

source:
  url: https://bitbucket.org/ruamel/yaml/get/{{ version }}.tar.gz
  sha256: 69bec987b5ac6ecf360c091e264e80b40df8fb004c394f730e30e79fdd91beec
  patches:
    - ordereddict_test.patch
      
build:
  number: 0
  no_link: .*\.(pyd|dll)  # [win]

requirements:
  build:
    - python
    - pip
    - toolchain
    - posix               # [win]
    - cython
    - yaml

  run:
    - python
    - yaml

test:
  requires:
    - pytest

  imports:
    - ruamel_yaml
    - ruamel_yaml.ext._ruamel_yaml

about:
  home: https://bitbucket.org/ruamel/yaml
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A patched copy of ruamel.yaml.

extra:
  recipe-maintainers:
    - jakirkham
